---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

dependencies:
  galaxy:
    collections:
      - ansible.windows
      - community.windows
      - community.general
      - ansible.utils
      - ansible.posix
      - chocolatey.chocolatey
      - microsoft.ad
  python:
    - requests-credssp > 1.2.0

options:
  package_manager_path: /usr/bin/microdnf
