---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8:latest'
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-vvv'
  
ansible_config: '../ansible.cfg'

dependencies:
  galaxy: requirements.yml
  # python: requirements.txt

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools
  append: |
    LABEL quay.expires-after="45d"
 
