---
version: 3
images:
    base_image:
        name: 'registry.redhat.io/ansible-automation-platform-25/de-minimal-rhel8:latest'

additional_build_files:
    # Can be used to resolve collections from private automation hub
    - src: ansible.cfg
      dest: configs

dependencies:
    galaxy: ansible-collections.yml
    python: python-packages.txt
    system: system-packages.txt

options:
    package_manager_path: /usr/bin/microdnf

additional_build_steps:
    prepend_base:
        - RUN $PYCMD -m pip install --upgrade pip setuptools
        - RUN $PYCMD -m pip install --upgrade --ignore-installed typing-extensions
        - RUN $PYCMD -m pip install --ignore-installed aiohttp==3.8.5
    prepend_galaxy:
        # Add custom ansible.cfg which defines collection install sources
        - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
        # AH_TOKEN is passed into the build command using a --build-arg
        # accept this as an ARG during this stage to reference later
        - ARG AH_TOKEN
        # Use the above ARG to define an environment variable holding
        # the token for resolving private collections
        - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN=$AH_TOKEN
    append_final:
        - RUN rm -f /etc/ansible/ansible.cfg
        - ENV PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.11/site-packages:/usr/local/lib64/python3.11/site-packages
