---
version: 3

images:
    base_image:
        name: 'registry.redhat.io/ansible-automation-platform-24/de-minimal-rhel8:latest'

additional_build_files:
    # Can be used to resolve collections from private automation hub
    - src: ansible.cfg
      dest: configs

dependencies:
    python:
        - aiohttp
        - aiokafka
        - requests
    system:
        - pkgconf-pkg-config [platform:rpm]
        - systemd-devel [platform:rpm]
        - gcc [platform:rpm]
        - python39-devel [platform:rpm]
    galaxy:
        collections:
            - name: ansible.eda
            - name: cloin.eda
            - name: cloin.datadog
            - name: ansible.utils
            - name: dynatrace.event_driven_ansible
            - name: cloin.prometheus
            - name: crowdstrike.falcon
options:
    package_manager_path: /usr/bin/microdnf

additional_build_steps:
    prepend_base:
        - RUN $PYCMD -m pip install --upgrade pip setuptools
    prepend_galaxy:
        # Add custom ansible.cfg which defines collection install sources
        - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
        # AH_TOKEN is passed into the build command using a --build-arg
        # accept this as an ARG during this stage to reference later
        - ARG AH_TOKEN
        # Use the above ARG to define an environment variable holding
        # the token for resolving private collections
        - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN=$AH_TOKEN
