---
version: 3
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel8:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner

additional_build_files:
  # Can be used to resolve collections from private automation hub
  - src: ansible.cfg
    dest: configs

options:
  package_manager_path: /usr/bin/microdnf
    
additional_build_steps:
  prepend_base:
    - RUN $PYCMD -m pip install --upgrade pip setuptools 
  prepend_galaxy:
    # Add custom ansible.cfg which defines collection install sources
    - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    # AH_TOKEN is passed into the build command using a --build-arg
    # accept this as an ARG during this stage to reference later
    - ARG AH_TOKEN
    # Use the above ARG to define an environment variable holding
    # the token for resolving private collections
    - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN=$AH_TOKEN
  append_base:
    - RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/awscliv2.zip"
    - RUN unzip /awscliv2.zip -d /aws
    - RUN /aws/aws/install
    - RUN curl "https://releases.hashicorp.com/terraform/1.10.3/terraform_1.10.3_linux_386.zip" -o "/terraform.zip"
    - RUN unzip /terraform.zip -d /terraform
    - RUN mv /terraform/terraform /bin
