# Workflow name
name: Workshop EE build

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main
    paths:
      - 'workshop_ee/**'

  # Schedule workflow run at 00:00 on Sunday
  schedule:
    - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-deploy-workflow:
    uses:  cloin/ee-builds/.github/workflows/deploy.yml@main
    with:
      EE_FOLDER_NAME: 'workshop_ee'
      EE_IMAGE_TAG: 'latest'
      QUAY_USER: 'acme_corp'
    secrets:
      REDHAT_USERNAME: ${{ secrets.REDHAT_USERNAME }}
      REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
      AH_TOKEN: ${{ secrets.AH_TOKEN }}
